[package]
name = "covey"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
color-eyre.workspace = true
toml.workspace = true
serde.workspace = true
ts-rs = { workspace = true, optional = true, features = ["serde-json-impl"] }
serde_json.workspace = true
futures.workspace = true
tracing.workspace = true
tokio = { workspace = true, features = ["fs", "process"] }
tonic.workspace = true
prost.workspace = true
az.workspace = true
dirs.workspace = true
parking_lot.workspace = true
covey-config = { path = "../covey-config" }

[build-dependencies]
tonic-build = "0.12.3"

[features]
ts-rs = ["dep:ts-rs"]
