[package]
name = "qpmu-manifest-macro"
version = "0.1.0"
edition = "2024"

[dependencies]
proc-macro-error2 = "2"
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true
qpmu-manifest = { path = "../qpmu-manifest" }

[lib]
proc-macro = true

[lints]
workspace = true
