[package]
name = "qpmu-manifest"
version = "0.1.0"
edition = "2024"

[dependencies]
proc-macro2 = "1.0.92"
quote = "1.0.38"
serde.workspace = true
syn = "2.0.92"
toml.workspace = true

[lints]
workspace = true
